### ISSUE TITLE
Create issues from steps on README

### ISSUE THREAD

**Issue by jfsiii** [nchnsn/othello#2]
Convert each item below into one or more issues.

You can even [add TODO lists in an issue](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments). So each one could be an issue, and then you could add the steps you want to accomplish in the description.

```
Step 1 Get Othello working no matter what means possible. Focus on ES5 and vanilla javascript if possible.

Step 2 Refactor game so that you are not using global variables, you are not copying pasting any code chunks, and think about scalability and memory management.

Step 3 Refactor code again to use Jquery and ES6.

Step 4 Refactor Code and write game in React.
```

**Comment by nchnsn** [comment]
Turned them all into milestones, removed the Jquery/ES6 rewrite, since will be using ES6 in react and alreay using jquery.
