### ISSUE TITLE
Publish site using GitHub Pages

### ISSUE THREAD

**Issue by jfsiii** [nchnsn/othello#4]
If you enable [GitHub Pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) people will be able to play the game online at https://nchnsn.github.io/othello/

This means people can play the game without cloning the repo and you don't have to host the game on your own. It's as simple as [enabling a setting and pushing code to a new branch](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/).

**Comment by nchnsn** [comment]
Got it up now.
